function Hd = bandpass(Fs)
%BANDPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the Signal Processing Toolbox 7.3.
% Generated on: 17-Jan-2020 13:17:50

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
% Fs = 250;  % Sampling Frequency

Fstop1 = 3;               % First Stopband Frequency
Fpass1 = 5;               % First Passband Frequency
Fpass2 = 38;              % Second Passband Frequency
Fstop2 = 40;              % Second Stopband Frequency
Dstop1 = 0.0001;          % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
